-- MySQL Script generated by MySQL Workbench
-- 07/13/16 12:09:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stages
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stages
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stages` DEFAULT CHARACTER SET utf8 ;
USE `stages` ;

-- -----------------------------------------------------
-- Table `stages`.`Entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`Entreprise` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Adresse` VARCHAR(500) NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stages`.`PropositionStage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`PropositionStage` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `sujet_propose` TEXT NULL,
  `DateProposition` DATE NULL,
  `Duree` INT NULL,
  `Remuneration` DECIMAL(10,2) NULL,
  `Entreprise_numero` INT NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_PropositionStage_Entreprise_idx` (`Entreprise_numero` ASC),
  CONSTRAINT `fk_PropositionStage_Entreprise`
    FOREIGN KEY (`Entreprise_numero`)
    REFERENCES `stages`.`Entreprise` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stages`.`Etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`Etudiant` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(145) NULL,
  `Prenom` VARCHAR(145) NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stages`.`Enseignant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`Enseignant` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(145) NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stages`.`Convention`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`Convention` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `RemunerationFinale` DECIMAL(10,2) NULL,
  `SujetMemoire` TEXT NULL,
  `DateDebut` DATE NULL,
  `DateSignature` DATE NULL,
  `DerniereDateVisiteEnseignant` DATE NULL,
  `Etudiant_numero` INT NOT NULL,
  `PropositionStage_numero` INT NOT NULL,
  `Enseignant_numero` INT NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_Convention_Etudiant1_idx` (`Etudiant_numero` ASC),
  INDEX `fk_Convention_PropositionStage1_idx` (`PropositionStage_numero` ASC),
  INDEX `fk_Convention_Enseignant1_idx` (`Enseignant_numero` ASC),
  CONSTRAINT `fk_Convention_Etudiant1`
    FOREIGN KEY (`Etudiant_numero`)
    REFERENCES `stages`.`Etudiant` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Convention_PropositionStage1`
    FOREIGN KEY (`PropositionStage_numero`)
    REFERENCES `stages`.`PropositionStage` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Convention_Enseignant1`
    FOREIGN KEY (`Enseignant_numero`)
    REFERENCES `stages`.`Enseignant` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stages`.`Etudiant_contact_Entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stages`.`Etudiant_contact_Entreprise` (
  `Etudiant_numero` INT NOT NULL AUTO_INCREMENT,
  `Entreprise_numero` INT NOT NULL,
  `DatePriseContact` DATE NULL,
  PRIMARY KEY (`Etudiant_numero`, `Entreprise_numero`),
  INDEX `fk_Etudiant_has_Entreprise_Entreprise1_idx` (`Entreprise_numero` ASC),
  INDEX `fk_Etudiant_has_Entreprise_Etudiant1_idx` (`Etudiant_numero` ASC),
  CONSTRAINT `fk_Etudiant_has_Entreprise_Etudiant1`
    FOREIGN KEY (`Etudiant_numero`)
    REFERENCES `stages`.`Etudiant` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etudiant_has_Entreprise_Entreprise1`
    FOREIGN KEY (`Entreprise_numero`)
    REFERENCES `stages`.`Entreprise` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
