-- MySQL Script generated by MySQL Workbench
-- 07/12/16 09:34:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema auto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema auto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auto` DEFAULT CHARACTER SET utf8 ;
USE `auto` ;

-- -----------------------------------------------------
-- Table `auto`.`CLIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto`.`CLIENT` (
  `clientId` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL,
  `prenom` VARCHAR(255) NULL,
  `adresse` VARCHAR(255) NULL,
  `dateNaissance` DATE NULL,
  PRIMARY KEY (`clientId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto`.`CD_ROM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto`.`CD_ROM` (
  `cdRomId` INT NOT NULL AUTO_INCREMENT,
  `editeur` VARCHAR(255) NULL,
  PRIMARY KEY (`cdRomId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto`.`SERIE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto`.`SERIE` (
  `serieId` INT NOT NULL AUTO_INCREMENT,
  `CD_ROM_cdRomId` INT NOT NULL,
  PRIMARY KEY (`serieId`),
  INDEX `fk_SERIE_CD_ROM1_idx` (`CD_ROM_cdRomId` ASC),
  CONSTRAINT `fk_SERIE_CD_ROM1`
    FOREIGN KEY (`CD_ROM_cdRomId`)
    REFERENCES `auto`.`CD_ROM` (`cdRomId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto`.`SEANCE_CODE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto`.`SEANCE_CODE` (
  `seanceId` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `heure` TIME NULL,
  `lieu` VARCHAR(255) NULL,
  `estExamen` TINYINT(1) NULL,
  `SERIE_serieId` INT NOT NULL,
  PRIMARY KEY (`seanceId`),
  INDEX `fk_SEANCE_CODE_SERIE1_idx` (`SERIE_serieId` ASC),
  CONSTRAINT `fk_SEANCE_CODE_SERIE1`
    FOREIGN KEY (`SERIE_serieId`)
    REFERENCES `auto`.`SERIE` (`serieId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto`.`QUESTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto`.`QUESTION` (
  `questionId` INT NOT NULL AUTO_INCREMENT,
  `intitule` VARCHAR(255) NULL,
  `reponse` VARCHAR(45) NULL,
  `niveauDifficulte` VARCHAR(45) NULL,
  `theme` VARCHAR(45) NULL,
  PRIMARY KEY (`questionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto`.`SERIE_has_QUESTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto`.`SERIE_has_QUESTION` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `SERIE_serieId` INT NOT NULL,
  `QUESTION_questionId` INT NOT NULL,
  INDEX `fk_SERIE_has_QUESTION_QUESTION1_idx` (`QUESTION_questionId` ASC),
  INDEX `fk_SERIE_has_QUESTION_SERIE1_idx` (`SERIE_serieId` ASC),
  PRIMARY KEY (`numero`),
  CONSTRAINT `fk_SERIE_has_QUESTION_SERIE1`
    FOREIGN KEY (`SERIE_serieId`)
    REFERENCES `auto`.`SERIE` (`serieId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERIE_has_QUESTION_QUESTION1`
    FOREIGN KEY (`QUESTION_questionId`)
    REFERENCES `auto`.`QUESTION` (`questionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto`.`CLIENT_has_SEANCE_CODE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto`.`CLIENT_has_SEANCE_CODE` (
  `CLIENT_clientId` INT NOT NULL,
  `SEANCE_CODE_seanceId` INT NOT NULL,
  `nbFautes` INT NULL,
  PRIMARY KEY (`CLIENT_clientId`, `SEANCE_CODE_seanceId`),
  INDEX `fk_CLIENT_has_SEANCE_CODE_SEANCE_CODE1_idx` (`SEANCE_CODE_seanceId` ASC),
  INDEX `fk_CLIENT_has_SEANCE_CODE_CLIENT1_idx` (`CLIENT_clientId` ASC),
  CONSTRAINT `fk_CLIENT_has_SEANCE_CODE_CLIENT1`
    FOREIGN KEY (`CLIENT_clientId`)
    REFERENCES `auto`.`CLIENT` (`clientId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENT_has_SEANCE_CODE_SEANCE_CODE1`
    FOREIGN KEY (`SEANCE_CODE_seanceId`)
    REFERENCES `auto`.`SEANCE_CODE` (`seanceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
