-- MySQL Script generated by MySQL Workbench
-- 07/13/16 11:21:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fouille
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fouille
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fouille` DEFAULT CHARACTER SET utf8 ;
USE `fouille` ;

-- -----------------------------------------------------
-- Table `fouille`.`Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fouille`.`Equipe` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(145) NULL,
  `sigle` VARCHAR(45) NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fouille`.`SitesFouille`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fouille`.`SitesFouille` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `Ville` VARCHAR(145) NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fouille`.`Parcelle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fouille`.`Parcelle` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `longueur` INT NULL,
  `largeur` INT NULL,
  `SitesFouille_numero` INT NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_Parcelle_SitesFouille1_idx` (`SitesFouille_numero` ASC),
  CONSTRAINT `fk_Parcelle_SitesFouille1`
    FOREIGN KEY (`SitesFouille_numero`)
    REFERENCES `fouille`.`SitesFouille` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fouille`.`Objet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fouille`.`Objet` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `designation` VARCHAR(145) NULL,
  `categorie` VARCHAR(45) NULL,
  `completude` VARCHAR(45) NULL,
  `conservation` VARCHAR(45) NULL,
  `dateDecouverte` DATE NOT NULL,
  `Equipe_numero` INT NOT NULL,
  `Parcelle_numero` INT NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_Objet_Equipe1_idx` (`Equipe_numero` ASC),
  INDEX `fk_Objet_Parcelle1_idx` (`Parcelle_numero` ASC),
  CONSTRAINT `fk_Objet_Equipe1`
    FOREIGN KEY (`Equipe_numero`)
    REFERENCES `fouille`.`Equipe` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Objet_Parcelle1`
    FOREIGN KEY (`Parcelle_numero`)
    REFERENCES `fouille`.`Parcelle` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fouille`.`Chercheurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fouille`.`Chercheurs` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(145) NULL,
  `prenom` VARCHAR(145) NULL,
  `fonction` VARCHAR(145) NULL,
  `Equipe_numero` INT NOT NULL,
  `directeur` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`numero`),
  INDEX `fk_Chercheurs_Equipe_idx` (`Equipe_numero` ASC),
  CONSTRAINT `fk_Chercheurs_Equipe`
    FOREIGN KEY (`Equipe_numero`)
    REFERENCES `fouille`.`Equipe` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fouille`.`Equipe_Fouille_SitesFouille`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fouille`.`Equipe_Fouille_SitesFouille` (
  `Equipe_numero` INT NOT NULL,
  `SitesFouille_numero` INT NOT NULL,
  `Date` DATE NULL,
  PRIMARY KEY (`Equipe_numero`, `SitesFouille_numero`),
  INDEX `fk_Equipe_has_SitesFouille_SitesFouille1_idx` (`SitesFouille_numero` ASC),
  INDEX `fk_Equipe_has_SitesFouille_Equipe1_idx` (`Equipe_numero` ASC),
  CONSTRAINT `fk_Equipe_has_SitesFouille_Equipe1`
    FOREIGN KEY (`Equipe_numero`)
    REFERENCES `fouille`.`Equipe` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipe_has_SitesFouille_SitesFouille1`
    FOREIGN KEY (`SitesFouille_numero`)
    REFERENCES `fouille`.`SitesFouille` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
